{% set name = "hopcroftkarp" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc6fc7ad348bbe5c9451f8116845c46ae26290c92b2dd14690aae2d55ba5e3a6

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - hopcroftkarp

about:
  home: https://github.com/sofiatolaosebikan/hopcroftkarp
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'a module to find a maximum matching in bipartite graphs'

extra:
  recipe-maintainers:
    - asmeurer
    - henrik227
